### ISSUE TITLE
Login is possible with any user/pass

### ISSUE THREAD

**Issue by gavinpham** [InsightVirtualPantry/VirtualPantry#5]
After creating account with username: gavinpham and password: password, I attempted to log in. That worked. However, I attempted to log in with username: goose password: goose and that also welcomed me in the same manner, directing me to the pantry page. 

Worked 2/2 times attempted. 

Gavin Pham gpham@smu.edu

**Comment by edjli2005** [comment]
Created account with username: 120gh0rep9u01!#$^U(!)% and password: [space] character. Worked 3/3 times with various sets of random characters.

Edward Li eli@smu.edu 214-991-6651

![selection_003](https://cloud.githubusercontent.com/assets/6685858/6834528/ba89a1fe-d302-11e4-8aeb-3690abd0c059.png)
